defaults:
  - _self_

device: cuda  # device used to generate and evaluate explanations: 'cpu' or 'cuda'

flags:
  enable_eval: True             # enable evaluation
  override_explanations: False  # if explanations exists already, override them
  override_evaluations: True    # if evaluations exists already, override them

model:
  pretrained_model_name_or_path: facebook/detr-resnet-50      # argument passed to `transformers.DetrForObjectDetection.from_pretrained`
  pretrained_processor_name_or_path: facebook/detr-resnet-50  # argument passed to `transformers.DetrImageProcessor.from_pretrained`

  # id2 label dictionary used to visualize the detections
  id2label:
    0: N/A,
    1: person,
    10: traffic light,
    11: fire hydrant,
    12: street sign,
    13: stop sign,
    14: parking meter,
    15: bench,
    16: bird,
    17: cat,
    18: dog,
    19: horse,
    2: bicycle,
    20: sheep,
    21: cow,
    22: elephant,
    23: bear,
    24: zebra,
    25: giraffe,
    26: hat,
    27: backpack,
    28: umbrella,
    29: shoe,
    3: car,
    30: eye glasses,
    31: handbag,
    32: tie,
    33: suitcase,
    34: frisbee,
    35: skis,
    36: snowboard,
    37: sports ball,
    38: kite,
    39: baseball bat,
    4: motorcycle,
    40: baseball glove,
    41: skateboard,
    42: surfboard,
    43: tennis racket,
    44: bottle,
    45: plate,
    46: wine glass,
    47: cup,
    48: fork,
    49: knife,
    5: airplane,
    50: spoon,
    51: bowl,
    52: banana,
    53: apple,
    54: sandwich,
    55: orange,
    56: broccoli,
    57: carrot,
    58: hot dog,
    59: pizza,
    6: bus,
    60: donut,
    61: cake,
    62: chair,
    63: couch,
    64: potted plant,
    65: bed,
    66: mirror,
    67: dining table,
    68: window,
    69: desk,
    7: train,
    70: toilet,
    71: door,
    72: tv,
    73: laptop,
    74: mouse,
    75: remote,
    76: keyboard,
    77: cell phone,
    78: microwave,
    79: oven,
    8: truck,
    80: toaster,
    81: sink,
    82: refrigerator,
    83: blender,
    84: book,
    85: clock,
    86: vase,
    87: scissors,
    88: teddy bear,
    89: hair drier,
    9: boat,
    90: toothbrush

explainer:
  score_threshold: 0.7    # explain only detections with confidence score >= score_threshold
  area_threshold: 0.1     # explain only detections with area >= area_threshold
  include_labels: all     # if 'all' then generate explanations for any label, otherwise specify a list of labels e.g. ['person', 'car']

# Information used if flags.enable_eval is set to True
evaluation:
  mode: deletion          # 'insertion' or 'deletion'
  percent_per_step: 0.01  # how much deletion/insertion of image tokens to do per step
  batch_size: 2           

  # This are used for visualizing the evaluation
  show_progress: True     # if set True, it will save the frames generated at each step in tensorboard
  d_t_color: [0, 0, 255]  # color of the explained detection (target)
  d_p_color: [255, 0, 0]  # color of the most similar detection in a step (proposed)
  mask_color: [0, 0, 0]   # color of the mask applied on the masked image tokens
  alpha: 0.7              # alpha value for mask

paths:
  images_dir: ''  # directory containing the images to explain
  output_dir: ''  # directory to save the results
